name: analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.5
  - numpy=2.2.6
  - scipy=1.16.0
  - pandas=2.3.1
  - matplotlib=3.10.0
  - pip
  - pip:
      - fracridge==2.0
      - nibabel==5.3.2
      - nilearn==0.12.0
      - nipype==1.10.0
      - scikit-learn==1.7.0
      - statsmodels==0.14.5
      - neuromaps
      - setuptools
      - netneurotools
      - brainsmash
      - glmsingle==1.2